Added new metric to capture any snapshotter error
gardener/etcd-backup-restore pull request #326
Opened 2021-04-14 10:49 UTC by aaronfern

**What this PR does / why we need it**:
Adding a new metric `etcdbr_snapshotter_failure` used as a blanket metric to capture any snapshotter error. This will be used to add an alert to the gardener prometheus dashboard to alert the DoD of any backup sidecar error wrt any snapshotter operation failure.
This is a precursor to allowing etcd to serve traffic when the backup sidecar is starting up/restarting 

**Which issue(s) this PR fixes**:
Fixes partially #325 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Added a new metric `etcdbr_snapshotter_failure` used as a blanket metric to capture any snapshotter error. 
```

2021-04-14 10:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/etcd-backup-restore?pullRequest=326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/etcd-backup-restore?pullRequest=326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/etcd-backup-restore?pullRequest=326) it.</sub>

2021-04-14 10:50 UTC, aaronfern commented
/invite @shreyas-s-rao

2021-04-14 10:55 UTC, aaronfern commented
/invite @amshuman-kr

2021-04-15 19:06 UTC, shreyas-s-rao requested changes
@aaronfern Thanks for the well-written first PR! I have added a few comments regarding using the `LabelError` constant from metrics package. Please address these changes. Thanks.

2021-04-16 06:21 UTC, shreyas-s-rao approved these changes

2021-04-21 12:56 UTC, merged