[WIP] To dynamically load IaaS credentials during runtime
gardener/etcd-backup-restore pull request #428
Opened 2022-02-03 17:18 UTC by ishan16696

**What this PR does / why we need it**:
To circumvent a required restart, `etcd-backup-restore` should re-read the credentials every time it performs any action on the bucket.

**To Dynamically load IaaS credentials during runtime:**

- [x] To circumvent a required restart, `etcd-backup-restore` should recreate/update the snapstore object  every time it performs any action on the bucket.
- [ ] Mount Kubernetes secrets into the container:
  - [x] AWS s3
  - [ ] Azure Blob Storage
  - [ ] Alicloud Object storage
  - [ ] Swift (Openstack)

**Which issue(s) this PR fixes**:
Fixes #422 

**Special notes for your reviewer**:

**Release note**:
```improvement operator

```

2022-02-08 13:00 UTC, timuthy requested changes
Thanks for the PR. I added some comments as feedback.

2022-02-08 13:00 UTC, timuthy commented on pkg/snapshot/snapshotter/snapshotter.go
> +	ssr.store, err = snapstore.GetSnapstore(ssr.snapstoreConfig)
Creating a new store object is related to some overhead, not only re-reading the credentials but also instantiating a new client, connection etc. (depends on cloud provider). WDYT about creating and saving a hash value of the currently used credentials and only create an entirely new Snapstore if the hash has changed?

2022-02-10 07:54 UTC, ishan16696 commented
Open a similar  PR for `master branch` https://github.com/gardener/etcd-backup-restore/pull/435

2022-02-11 08:00 UTC, timuthy commented
> Open a similar PR for `master branch` #435

Can you address my comments for https://github.com/gardener/etcd-backup-restore/pull/435 and we close this one? As discussed, there is currently no motivation to release this feature as hot fix.

2022-02-11 08:05 UTC, closed without merging

2022-02-11 11:17 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +			Credentials: credentials.NewStaticCredentials(prefixString+awsConfig.AccessKeyID, prefixString+awsConfig.SecretAccessKey, ""),
> This is presumably not the right place to add prefixString

this is how it is currently done  check [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapstore/s3_snapstore.go#L79)

> Those source secrets will probably be configured by setting another env var like SOURCE_AWS_APPLICATION_CREDENTIALS

I'm not very sure about this Source thing .... I think it is added by CPM for `copy subcommand`. We need to check with them as we are not breaking their changes.

2022-02-11 11:30 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +	for _, file := range files {
the only benefit it has that it kindof checks whether file exists for not

2022-02-11 11:32 UTC, timuthy commented on pkg/snapstore/s3_snapstore.go
> +			Credentials: credentials.NewStaticCredentials(prefixString+awsConfig.AccessKeyID, prefixString+awsConfig.SecretAccessKey, ""),
> this is how it is currently done check [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapstore/s3_snapstore.go#L79)

Well, as far as I can tell there is a huge difference.
In the current implementation, the **prefix is used for reading env vars** (-> `os.Getenv(prefixString+awsAcessKeyID`) whereas you use it to change the credentials (-> `prefixString+awsConfig.AccessKeyID` and `prefixString+awsConfig.SecretAccessKey`)

2022-02-11 11:32 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +
what's the benefit of checking? 
even if it’s not set then storage provider will eventually through error

2022-02-11 13:54 UTC, timuthy commented on pkg/snapstore/s3_snapstore.go
> +
The advantage is that we specifically report about the problem, e.g., "file named accessKeyID is missing". The storage provider message will be different, i.e., unrelated to the integration pattern that we use. Another advantage is that we exit early and stop wasting further resources.