Assigned the correct Peer Address to Etcd after it restores from the backup-bucket.
gardener/etcd-backup-restore pull request #505
Opened 2022-07-15 06:59 UTC by ishan16696

**What this PR does / why we need it**:
When we create a new etcd cluster(size=1) then Peer address is correct, but after restoration of Etcd by backup-restore the Peer Address is not seems to be correct. This PR fixes this bug.

**Which issue(s) this PR fixes**:
Fixes #500 

**Special notes for your reviewer**:
Please test Scale up feature only after this [PR](https://github.com/gardener/etcd-backup-restore/pull/501) get merge as it contains one fix of Scale up feature.

**Release note**:
```improvement operator
Assigned the correct Peer address to the Etcd after it restored from backup-bucket.
```

2022-07-18 05:13 UTC, aaronfern requested changes
Looks good, just a nit

2022-07-18 08:41 UTC, ishan16696 commented on pkg/member/member_control.go
> +		m.logger.Infof("Member %v with ID: %v have been promoted", member.GetName(), member.GetID())
done

2022-07-18 15:34 UTC, aaronfern commented
I tested this PR and it's working as expected
However I also want to test cluster scale-up with this PR after #501 is merged

2022-07-19 09:04 UTC, ishan16696 commented
Hi @aaronfern ,
I have rebased the PR on master after merging #501. you can test it now for scale up feature before and after triggering the restoration.

2022-07-20 09:43 UTC, merged