[Feat] min-chunk-size flag
gardener/etcd-backup-restore pull request #545
Opened 2022-10-05 12:54 UTC by louisportay

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

none

**Special notes for your reviewer**:

**Release note**:

category: improvement
target_group: user

addition of min-chunk-size flag allows to fine-tune multi-part upload across different store providers

2022-10-05 12:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/etcd-backup-restore?pullRequest=545) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/etcd-backup-restore?pullRequest=545) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/etcd-backup-restore?pullRequest=545) it.</sub>

2022-10-06 04:29 UTC, ishan16696 commented
Can you please add an appropriate release note for this PR?

2022-10-06 13:01 UTC, louisportay commented
Done, do not hesitate to tell me if I need to change the format

2022-11-02 12:51 UTC, louisportay commented
up

2022-11-04 17:53 UTC, ishan16696 commented
sorry for the delay I will try to review it at earliest.

2022-11-11 09:24 UTC, ishan16696 commented
Please fix the unit tests [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapstore/abs_snapstore_test.go#L48) and [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapstore/snapstore_test.go#L104-L131)

2022-11-11 09:24 UTC, ishan16696 requested changes
few nits.

2022-11-11 10:07 UTC, ishan16696 commented
I have also updated the release note. Hope that's fine.

2022-11-21 13:27 UTC, louisportay commented
any action needed on my side ?

2022-11-22 10:25 UTC, ishan16696 commented
> any action needed on my side ?

I will update after testing this PR.

2022-11-25 16:32 UTC, ishan16696 requested changes
I have tested the PR, it is working fine. Overall looks good.
Just one nit:

2022-11-25 16:32 UTC, ishan16696 commented on pkg/types/snapstore.go
> +		return fmt.Errorf("min chunk size for multi-part chunk upload should be greater than 5 MiB")
```suggestion
		return fmt.Errorf("min chunk size for multi-part chunk upload should be greater than or equal to 5 MiB")
```

2022-12-02 05:58 UTC, ishan16696 approved these changes

2022-12-02 05:58 UTC, merged