⬆️ Upgrade the `go.etcd.io/etcd` dependency to `v3.4.34`, and all other direct dependencies
gardener/etcd-backup-restore pull request #795
Opened 2024-10-21 08:16 UTC by renormalize

**What this PR does / why we need it**:

* Upgrade all direct dependencies to the latest versions.
* Upgrade the etcd version to `v3.4.34`.
* Use the `Restoration` API provided by etcd to trigger a restore instead of relying on copied code for restoration.
* Standardize the `yaml` dependency to `sigs.k8s.io/yaml`.
* Replace the deprecated `github.com/golang/mock` dependency with `go.uber.org/mock`.
* Upgrade the etcd version to `v3.4.34` in the integration tests.

**Which issue(s) this PR fixes**:
Fixes #792 

**Special notes for your reviewer**:

Only commits bf0b0f0fca54fc2486886b1c1906a0409ed3040c and e617f8978b203d1486e963c2969865fbcf731c3a have code changes which are relevant. Every other commit only touches `go.mod` and `go.sum`.

cc @seshachalam-yv 

**Release note**:

```improvement user
etcd-backup-restore now uses etcd v3.4.34 for both the client as well as the embedded etcd during restoration. All direct dependencies are also upgraded to rely on this version.
```

2024-10-21 09:10 UTC, seshachalam-yv requested changes

2024-10-21 09:18 UTC, renormalize commented on pkg/snapshot/restorer/restorer.go
> +	defer rc.Close()
Thanks for finding this! An obvious miss from my side.

2024-10-21 13:12 UTC, seshachalam-yv commented on pkg/snapshot/restorer/restorer.go
>  		r.logger.Warnf("Base snapshot path not provided. Will do nothing.")
```suggestion
	baseSnapshotPath := path.Join(ro.BaseSnapshot.SnapDir, ro.BaseSnapshot.SnapName)
	if baseSnapshotPath == "" {
		r.logger.Warn("Base snapshot path not provided. Skipping restoration from base snapshot.")
		return nil
	}

	r.logger.Infof("Restoring from base snapshot: %s", baseSnapshotPath)
```

2024-10-21 13:12 UTC, seshachalam-yv commented on pkg/snapshot/restorer/restorer.go
> +		return fmt.Errorf("failed to fetch the base snapshot from the object store with error: %w", err)
```suggestion
		return fmt.Errorf("failed to determine snapshot compression policy: %w", err)
```

2024-11-06 13:18 UTC, seshachalam-yv commented
It appears that we are currently referencing etcd version 3.4.13 in the following files:

- [.ci/integration_test](https://github.com/renormalize/etcd-backup-restore/blob/90087a7230362f779b592d7b68e3db85a78320b3/.ci/integration_test#L310)
- [.ci/performance_regression_test](https://github.com/renormalize/etcd-backup-restore/blob/90087a7230362f779b592d7b68e3db85a78320b3/.ci/performance_regression_test#L34)
- [chart/etcd-backup-restore/values.yaml](https://github.com/renormalize/etcd-backup-restore/blob/90087a7230362f779b592d7b68e3db85a78320b3/chart/etcd-backup-restore/values.yaml#L5)
- [docs/development/testing_and_dependencies.md](https://github.com/renormalize/etcd-backup-restore/blob/etcd-v3.4.34/docs/development/testing_and_dependencies.md?plain=1#L45)

Could you please update these references to etcd version 3.4.3?

2024-11-06 13:29 UTC, seshachalam-yv reviewed
Overall, the changes look good to me. Thank you, @renormalize, for upgrading the etcd version.

2024-11-07 06:23 UTC, renormalize commented
Thanks for your review @seshachalam-yv!

Regarding your comments:

- The version mentioned here [.ci/integration_test](https://github.com/renormalize/etcd-backup-restore/blob/90087a7230362f779b592d7b68e3db85a78320b3/.ci/integration_test#L310) is just used for the echo, which I missed. Thanks for pointing it out.
The tests already were running with `v3.4.34` thankfully due to the change in this [line](https://github.com/renormalize/etcd-backup-restore/blob/90087a7230362f779b592d7b68e3db85a78320b3/.ci/integration_test#L73).

- The following will have their "etcd" images, i.e. `etcd-custom-image` replaced with `etcd-wrapper`. I've added TODOs to ensure that when a newer release of `etcd-wrapper` is made with the  etcd version as `v3.4.34`, the references will be changed here. Until then, I've changed it to the latest release of `etcd-wrapper`.
  - [.ci/performance_regression_test](https://github.com/renormalize/etcd-backup-restore/blob/90087a7230362f779b592d7b68e3db85a78320b3/.ci/performance_regression_test#L34)
  - [chart/etcd-backup-restore/values.yaml](https://github.com/renormalize/etcd-backup-restore/blob/90087a7230362f779b592d7b68e3db85a78320b3/chart/etcd-backup-restore/values.yaml#L5)
  - [docs/development/testing_and_dependencies.md](https://github.com/renormalize/etcd-backup-restore/blob/etcd-v3.4.34/docs/development/testing_and_dependencies.md?plain=1#L45)

2024-11-07 09:34 UTC, renormalize commented
@seshachalam-yv 

I've run etcd-druid e2e tests with changes proposed from this PR, along with the changes proposed in https://github.com/gardener/etcd-wrapper/pull/30.

I overrode the `etcd-backup-restore` dependency in `etcd-druid` with the latest commit of this PR.

All tests pass.

<details>

<summary><code>make ci-e2e-kind</code></summary>

```
➜  etcd-druid git:(etcd-v3.4.34) ✗ make ci-e2e-kind                       
Creating local docker registry...
bdc16e1971652fe76195d22d055913be04bee78d99fc72ddbc53ead32f85d1f3
Generating kind cluster config...
Creating cluster "etcd-druid-e2e" ...
 ✓ Ensuring node image (kindest/node:v1.29.8) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-etcd-druid-e2e"
You can now use your cluster with:

kubectl cluster-info --context kind-etcd-druid-e2e

Have a nice day! 👋
Initializing local docker registry...
configmap/local-registry-hosting created

📌 NOTE: To target the newly created KinD cluster, please run the following command:

    export KUBECONFIG=/Users/renormalize/go/src/github.com/gardener/etcd-druid/hack/kind/kubeconfig

node/etcd-druid-e2e-control-plane condition met
deployment.apps/localstack created
service/localstack created
Waiting for deployment "localstack" rollout to finish: 0 of 1 updated replicas are available...
deployment "localstack" successfully rolled out
pod/localstack-7f769fd7dc-p6j5c condition met
namespace/e2e-test created
-------------------
Setting up environment
-------------------
namespace/e2e-test unchanged
No tags generated
Starting test...
Starting deploy...
Starting pre-deploy hooks...
Deleting previous job
No resources found
Completed pre-deploy hooks
 - configmap/aws-infra-common created
 - configmap/aws-run-script created
 - secret/aws-infra-secret created
 - job.batch/aws-infra-job created
Starting post-deploy hooks...
Wait until job is ready
job.batch/aws-infra-job condition met
Completed post-deploy hooks
You can also run [skaffold run --tail] to get the logs

-------------------
Deploying Druid
-------------------
Generating tags...
 - europe-docker.pkg.dev/gardener-project/public/gardener/etcd-druid -> localhost:5001/europe-docker_pkg_dev_gardener-project_public_gardener_etcd-druid:v0.23.0-8-gd2047f4a-dirty
Checking cache...
 - europe-docker.pkg.dev/gardener-project/public/gardener/etcd-druid: Not found. Building
Starting build...
Found [kind-etcd-druid-e2e] context, using local docker daemon.
Building [europe-docker.pkg.dev/gardener-project/public/gardener/etcd-druid]...
Target platforms: [linux/arm64]
Using base gcr.io/distroless/static-debian11:nonroot@sha256:63ebe035fbdd056ed682e6a87b286d07d3f05f12cb46f26b2b44fc10fc4a59ed for github.com/gardener/etcd-druid
Using build config europe-docker.pkg.dev/gardener-project/public/gardener/etcd-druid for github.com/gardener/etcd-druid
Building github.com/gardener/etcd-druid for linux/arm64/v8
Publishing localhost:5001/europe-docker_pkg_dev_gardener-project_public_gardener_etcd-druid:v0.23.0-8-gd2047f4a-dirty
Published localhost:5001/europe-docker_pkg_dev_gardener-project_public_gardener_etcd-druid:v0.23.0-8-gd2047f4a-dirty@sha256:e4fa4b60fa3143d6dd5c3118332bfecef1162071370af880358c9a9de1ef7c8b
Build [europe-docker.pkg.dev/gardener-project/public/gardener/etcd-druid] succeeded
Starting test...
Tags used in deployment:
 - europe-docker.pkg.dev/gardener-project/public/gardener/etcd-druid -> localhost:5001/europe-docker_pkg_dev_gardener-project_public_gardener_etcd-druid:v0.23.0-8-gd2047f4a-dirty@sha256:e4fa4b60fa3143d6dd5c3118332bfecef1162071370af880358c9a9de1ef7c8b
Starting deploy...
Helm release etcd-druid not installed. Installing...
NAME: etcd-druid
LAST DEPLOYED: Thu Nov  7 14:46:32 2024
NAMESPACE: e2e-test
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for deployments to stabilize...
 - e2e-test:deployment/etcd-druid is ready.
Deployments stabilized in 2.106 seconds
You can also run [skaffold run --tail] to get the logs

-------------------
Running e2e tests
-------------------
Running Suite: e2e Suite - /Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e
========================================================================================
Random Seed: 1730971000

Will run 8 of 8 specs
Running in parallel across 11 processes
------------------------------
[BeforeSuite] PASSED [0.045 seconds]
[BeforeSuite] 
/Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:67

  Timeline >>
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"ca-etcd-aws","namespace":"shoot"}}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"etcd-backup-aws","namespace":"shoot"}}
  << Timeline
------------------------------
[BeforeSuite] PASSED [0.048 seconds]
[BeforeSuite] 
/Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:67

  Timeline >>
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"ca-etcd-aws","namespace":"shoot"}}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"etcd-backup-aws","namespace":"shoot"}}
  << Timeline
------------------------------
[BeforeSuite] PASSED [0.048 seconds]
[BeforeSuite] 
/Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:67

  Timeline >>
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"ca-etcd-aws","namespace":"shoot"}}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"etcd-backup-aws","namespace":"shoot"}}
  << Timeline
------------------------------
[BeforeSuite] PASSED [0.048 seconds]
[BeforeSuite] 
/Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:67

  Timeline >>
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"ca-etcd-aws","namespace":"shoot"}}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"etcd-backup-aws","namespace":"shoot"}}
  << Timeline
------------------------------
[BeforeSuite] PASSED [0.048 seconds]
[BeforeSuite] 
/Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:67

  Timeline >>
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"ca-etcd-aws","namespace":"shoot"}}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"etcd-backup-aws","namespace":"shoot"}}
  << Timeline
------------------------------
[BeforeSuite] PASSED [0.049 seconds]
[BeforeSuite] 
/Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:67

  Timeline >>
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"ca-etcd-aws","namespace":"shoot"}}
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating secret","secret":{"name":"etcd-backup-aws","namespace":"shoot"}}
  << Timeline
------------------------------
[BeforeSuite] PASSED [0.048 seconds]
[BeforeSuite] 
/Users/renormalize/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:67

  Timeline >>
  {"level":"info","ts":"2024-11-07T14:46:50+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024- [...]

2024-11-07 10:00 UTC, seshachalam-yv approved these changes

2024-11-07 10:07 UTC, anveshreddy18 commented
/assign

2024-11-08 08:28 UTC, merged