Docs: Enhance immutable snapshots guide with detailed instructions
gardener/etcd-backup-restore pull request #811
Opened 2024-12-03 03:51 UTC by seshachalam-yv

**What this PR does / why we need it**:

This PR enhances the documentation for enabling immutable snapshots in `etcd-backup-restore`. It provides a comprehensive guide with detailed instructions for configuring bucket-level immutability on Google Cloud Storage (GCS) and Azure Blob Storage (ABS). The updated guide includes:

- A **Terminology** section for clarity and consistent use of terms.
- Detailed steps for configuring retention policies and locking them.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
- The file `docs/usage/immutable_snapshots.md` has been revised and renamed to `docs/usage/enabling_immutable_snapshots.md` to better reflect its content.

cc: @renormalize @ishan16696 

**Release note**:

```improvement operator
Enhanced the documentation for enabling immutable snapshots in `etcd-backup-restore`, providing detailed guidance and best practices for configuring bucket-level immutability on Google Cloud Storage and Azure Blob Storage.
```

2024-12-03 09:11 UTC, renormalize requested changes
Thank you very much for the documentation @seshachalam-yv!

2024-12-03 09:11 UTC, renormalize commented on docs/usage/enabling_immutable_snapshots.md
> +You can set a time-based retention policy on your bucket/container. The retention policy specifies the minimum duration for which the objects must remain immutable.
Can a line suggesting configuring the policy is also achievable in the cloud provider's respective console/portal, the way this doc currently suggests for adding tags to objects?

2024-12-03 09:11 UTC, renormalize commented on docs/usage/enabling_immutable_snapshots.md
> +You can modify an unlocked retention policy to adjust the retention period or to allow additional writes to the bucket/container.
https://github.com/gardener/etcd-backup-restore/pull/811#discussion_r1867311558

2024-12-03 11:15 UTC, seshachalam-yv commented on docs/usage/enabling_immutable_snapshots.md
> +- **Retention Policy**: A configuration that specifies a minimum period during which objects in a bucket/container are protected from deletion or modification.
Replaced 'Retention Policy' with 'Immutability Policy' to avoid confusion.

2024-12-03 11:18 UTC, seshachalam-yv commented on docs/usage/enabling_immutable_snapshots.md
> +- **Immutability**: A state where objects cannot be modified or deleted until the retention period expires.
Fixed

2024-12-03 11:18 UTC, seshachalam-yv commented on docs/usage/enabling_immutable_snapshots.md
> +- **Locking**: The action of making a retention policy permanent, preventing any reduction or removal of the retention period.
Fixed

2024-12-03 11:18 UTC, seshachalam-yv commented on docs/usage/enabling_immutable_snapshots.md
> +Currently, `etcd-backup-restore` supports bucket-level immutability for GCS and ABS. Support for AWS S3 is planned for a future release.
Removed

2024-12-03 11:23 UTC, seshachalam-yv commented on docs/usage/enabling_immutable_snapshots.md
> +   **Caution:** Locking is permanent and cannot be undone.
Fixed

2024-12-03 11:32 UTC, seshachalam-yv commented
Thanks @renormalize for reviewing. I've addressed all your review comments.

2024-12-05 10:03 UTC, renormalize approved these changes
Thanks for the PR @seshachalam-yv!

I've pointed out one comment again which you'd missed. Other than that, the doc looks great.

2024-12-05 10:03 UTC, renormalize commented on docs/usage/enabling_immutable_snapshots.md
> +   **Caution:** Once locked, the policy cannot be removed or decreased.
Can this be moved before the steps and changed to a `[!CAUTION]` like it is for GCS too?

2024-12-05 11:04 UTC, merged