Update Helm Charts for Single Member Etcd Cluster
gardener/etcd-backup-restore pull request #813
Opened 2024-12-18 10:00 UTC by anveshreddy18

**What this PR does / why we need it**:

This PR updates the outdated helm charts required to setup a single member etcd cluster with etcd-wrapper and etcd-backup-restore as containers in a pod. 

The changes include: 
- updating basic charts to run `etcd-wrapper` with distroless `etcd-backup-restore`
- correcting TLS paths and secrets
- updating cloud provider related parameters
- adding emulator support, etc

**Which issue(s) this PR fixes**:
Partially Fixes #708 

**Special notes for your reviewer**:

Currently tested with the following cloud providers & their emulators: 
- [x] GCP
- [x] AWS
- [x] AZURE 

The remaining providers are to be tested yet.

**Release note**:

```improvement user
update the helm charts for deploying single member etcd
```

2024-12-19 08:13 UTC, ishan16696 commented
Can you also capture somewhere in doc that right now, only nonHA etcd cluster can be deployed by helm charts for following providers.

2024-12-19 08:22 UTC, anveshreddy18 commented
Sure @ishan16696, will mention that.

2024-12-31 08:26 UTC, shreyas-s-rao requested changes
@anveshreddy18 thanks a lot for taking up the long-pending task of updating the helm charts! Few comments from my side, PTAL:
- Overall, I would like the charts to support multinode etcd clusters as well, as a static configuration. Since you've already introduced many peer TLS related artefacts in the chart, it should be easy to support multinode etcd clusters too. Moreover, it would be beneficial to have etcd-backup-restore charts support multinode etcd clusters, which are more widely used than single-node clusters. 
- please add newlines at the end of files - it's just good practice.
- Please add `etcd-peer-ca-secret.yaml` and `etcd-peer-server-tls-secret.yaml` files, to support multinode etcd clusters

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcdbr-server-tls-secret.yaml
> +  tls.key: {{ .Values.backupRestoreTLS.serverTLS.key | b64enc }}
Adapt the value paths based on the above change.

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcdbr-client-tls-secret.yaml
> +  tls.key: {{ .Values.backupRestoreTLS.clientTLS.key | b64enc }}
Same as above

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcdbr-ca-secret.yaml
> +  bundle.crt: {{ .Values.backupRestoreTLS.caBundle | b64enc }}
Same as above

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-server-tls-secret.yaml
> +  tls.key: {{ .Values.etcdTLS.serverTLS.key | b64enc }}
Same as above

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-client-tls-secret.yaml
> +  tls.key: {{ .Values.etcdTLS.clientTLS.key | b64enc }}
Same as above

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-ca-secret.yaml
> +  bundle.crt: {{ .Values.etcdTLS.caBundle | b64enc }}
Same as above

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/values.yaml
Restructure `servicePorts` to the following:
```
servicePorts:
  etcd:
    client: 2379
    server: 2380 # check whether server port is really necessary, since it is actually just the peer port
    peer: 2380
    etcdBackupRestore
      server: 8080
```

Remove `server` port, and replace its usage across the template files with `peer` port instead, which is the correct terminology.

Also, this is a stretch, but I see that etcd-wrapper exposes an HTTP server of its own, on port 9095 by default, and is currently not configurable - [ref](https://github.com/gardener/etcd-wrapper/blob/f3937f13ffc542493dfbb04ea920f27c73e68328/internal/app/readycheck.go#L24). Can you please also take up the task of raising a PR to expose that out of etcd-wrapper, and add a port for it here called `etcd.wrapperServer` ? This need not be part of this PR, but needs to be done in the future, to ensure configurability of the components.

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-configmap.yaml
>  {{- if .Values.etcdTLS }}
Please also add peer TLS information configs here, based on whether peer TLS is enabled or not in `values.yaml`.

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
> +{{- if .Values.backup.storageProvider}}
I like that you have segregated the flags under different headers for better readability. Thanks!

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>          - name: "AZURE_EMULATOR_ENABLED"
You can now get rid of `AZURE_EMULATOR_ENABLED` env var, after rebasing on latest master which includes https://github.com/gardener/etcd-backup-restore/pull/819

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>          - name: "GOOGLE_EMULATOR_ENABLED"
Same as above, for `GOOGLE_EMULATOR_ENABLED` env var as well.

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>  {{- if .Values.etcdTLS }}
Check and include peer TLS secrets as well

2024-12-31 08:26 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>  {{- if .Values.etcdTLS }}
Same as above

2024-12-31 08:29 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>    replicas: 1
Additionally to my previous review, please make this field configurable via values.yaml, to support multinode etcd clusters.

2025-01-07 08:56 UTC, anveshreddy18 commented on chart/etcd-backup-restore/values.yaml
> +  etcdConnectionTimeout: "5m"
I just wanted to give more timeout than 30s because I see context deadline exceeded msgs often in the logs. Then I referred what druid sets it by default and chose that here also. 

That said, I don't have any particular reason to prove that "5m" will be required. Pls let me know if you want a specific comment here.

2025-01-09 08:02 UTC, shreyas-s-rao requested changes
@anveshreddy18 thanks a lot for enabling support for multi-node etcd clusters via charts! I have a few more follow-up comments. PTAL, thanks

2025-01-09 08:02 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/serviceaccount.yaml
Related to the previous comment, I now wonder whether we even need the serviceaccount in the first place, for an etcd cluster not managed by etcd-druid.

2025-01-09 08:02 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/role.yaml
Same as above

2025-01-09 08:02 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/rolebinding.yaml
Same as above

2025-01-09 12:12 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>  {{- end }}
`backup-restore` need access to `sts` to check for scale-up annotation to determine whether the cluster is `new` or `existing` [ref](https://github.com/gardener/etcd-backup-restore/blob/0b4ed5079aba0e056966205a957a6805d74dfb48/pkg/miscellaneous/miscellaneous.go#L441-L457). So for `multi-node` this becomes a prerequisite unfortunately. 

Hence I've created the role, rolebinding and bind it to a custom serviceAccount as the default one won't have access to `sts`. But that said all we need is a `get` role for `sts` so I'll be removing all other roles.

2025-01-09 12:13 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
> +        - --k8s-heartbeat-duration=10s
Yes, we do not need `k8s-heartbeat-duration`, that was a miss from my side. I'll be removing this as well. Thanks for catching this.

2025-01-09 12:14 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/serviceaccount.yaml
Pls refer the above [comment](https://github.com/gardener/etcd-backup-restore/pull/813#discussion_r1908681938).

2025-01-09 12:15 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/role.yaml
Pls refer the above [comment](https://github.com/gardener/etcd-backup-restore/pull/813#discussion_r1908681938).

2025-01-09 12:15 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/rolebinding.yaml
Pls refer the above [comment](https://github.com/gardener/etcd-backup-restore/pull/813#discussion_r1908681938).

2025-01-09 12:18 UTC, anveshreddy18 commented on chart/etcd-backup-restore/values.yaml
> +    tag: v0.3.0
Oh nice. I thought to use but didn't as the PR to add `latest` tag was added recently and we haven't made a release since then. But I see the `latest` tag on `v0.3.0` as well, have you added that? 

Thanks will update this.

2025-01-09 12:20 UTC, anveshreddy18 commented on chart/etcd-backup-restore/values.yaml
> +    tag: v0.33.0-dev-e1690dd6ea14ca889d357307018ba2e53ced5203
I'm afraid we can't use the `latest` tag yet as `etcdbr` release has not happened yet which contains the necessary changes required for the helm charts to work. The PR I'm talking about: https://github.com/gardener/etcd-backup-restore/pull/819

2025-01-09 12:40 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>  {{- end }}
But this creates a hard dependency for etcdbr to require a client to the cluster it runs within, which is not correct. I would suggest removing this dependency, quite easily in fact. If a k8s client is not configured ([ref](https://github.com/gardener/etcd-backup-restore/blob/d5f4ef45701983fa862bb8eddb2d2390743e29b3/pkg/server/httpAPI.go#L439)), then instead of returning error, etcdbr should print a warning and default to `new` state for the cluster. `existing` state only makes sense for the scale-up case, but since the charts don't support scale-up, the state should be defaulted to `new`, and there should be no need for etcdbr to make a k8s API call. Can you please make this change?

2025-01-09 12:42 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/values.yaml
> +    tag: v0.3.0
Yes I had added this manually after our previous discussion in https://github.com/gardener/etcd-backup-restore/pull/743#discussion_r1900374564

2025-01-09 12:44 UTC, shreyas-s-rao commented on chart/etcd-backup-restore/values.yaml
> +    tag: v0.33.0-dev-e1690dd6ea14ca889d357307018ba2e53ced5203
Ok, got it. Can you please add an issue for this with milestone for v0.33.0, so that we don't miss this when cutting the release? Similar to https://github.com/gardener/etcd-druid/issues/960

2025-01-09 13:37 UTC, anveshreddy18 commented on chart/etcd-backup-restore/values.yaml
Have raised the issue: https://github.com/gardener/etcd-wrapper/issues/41
Will raise the PR as well.

2025-01-09 13:38 UTC, anveshreddy18 commented on chart/etcd-backup-restore/values.yaml
> +    tag: v0.33.0-dev-e1690dd6ea14ca889d357307018ba2e53ced5203
Link to the issue: https://github.com/gardener/etcd-backup-restore/issues/829

2025-01-15 09:43 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/etcd-statefulset.yaml
>  {{- end }}
On a slack conversation with @shreyas-s-rao, we have decided that we can let them as is for now and emulate what druid does currently. But going forward i.e in `etcd-steward`, we need to rethink of this hard dependency on k8s client for a multi-node cluster.

2025-01-15 09:43 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/serviceaccount.yaml
Closing with comment: https://github.com/gardener/etcd-backup-restore/pull/813#discussion_r1916248444

2025-01-15 09:43 UTC, anveshreddy18 commented on chart/etcd-backup-restore/templates/rolebinding.yaml
Closing with comment: https://github.com/gardener/etcd-backup-restore/pull/813#discussion_r1916248444

2025-01-15 15:33 UTC, shreyas-s-rao approved these changes
@anveshreddy18 thanks a lot for making the requested changes and enabling the charts to deploy multi-node etcd clusters!
/lgtm

2025-01-15 16:38 UTC, merged