Add `Bucket Lock` immutable objects support for AWS S3
gardener/etcd-backup-restore pull request #818
Opened 2024-12-24 05:45 UTC by ishan16696

**What this PR does / why we need it**:
This PR enables backup-restore to handle AWS S3's object lock mechanism which will make snapshots taken by backup-restore immutable. It also adjusted the Restoration and garbage collector functionality to handle immutable snapshots for S3 object store.

**Which issue(s) this PR fixes**:
Fixes #777 

**Special notes for your reviewer**:
These case I have tested:

For Restoration functionality
  - [x] Restoration functionality of backup-restore should work with buckets which don't have bucket/object lock enabled (Backward compatibility).
  - [x] Restoration functionality of backup-restore should work with buckets which have both versioned immutable as well as non-immutable, non-versioned snapshots present.
  - [x] Restoration functionality of backup-restore should work with buckets which have only immutable versioned snapshots(full as well as delta) present.

For Garbage collection of snapshots:
  - [x] Backward compatibility with buckets which don't have immutability enabled.
  - [x] GC should work with buckets which have both immutable as well as non immutable objects.
  - [x] GC should work with buckets which have only immutable objects.

**Release note**:

```noteworthy operator
etcd-backup-restore now supports immutable objects for storage provider: AWS S3, provided by the [Bucket Lock](https://aws.amazon.com/s3/features/object-lock/) feature.
```

```noteworthy operator
Snapshots garbage collection performed by etcd-backup-restore (if enabled) for S3 is performed only when the snapshots's retention period get expires.
```

```noteworthy operator
Support for Bucket lock (S3) in etcd-backup-restore is backward compatible. For more info please refer to this doc: https://github.com/gardener/etcd-backup-restore/blob/master/docs/usage/immutable_snapshots.md
```

2025-01-02 14:30 UTC, shreyas-s-rao requested changes
@ishan16696 thanks for the well-written PR and the docs. I have a few nits. PTAL, thanks.

2025-01-02 14:30 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +								// To avoid API calls for each snapshots, backup-restore is calculating the "ImmutabilityExpiryTime" using bucket retention period.
```suggestion
								// To get S3 object's "RetainUntilDate" or "ImmutabilityExpiryTime", backup-restore need to make an API call for each snapshot.
								// To avoid API calls for each snapshot, backup-restore is calculating the "ImmutabilityExpiryTime" using bucket retention period.
```

2025-01-02 14:30 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +								_, bucketImmutableExpiryTimeInDays, err = GetBucketImmutabilityTime(s)
How is `bucketImmutableExpiryTimeInDays` being used here? The snapshot gets added to the `snapList` without setting `snap.ImmutabilityExpiryTime`, which doesn't seem right. Can you please confirm?

2025-01-02 14:30 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +					logrus.Warnf("Snapshot: %s with versionID: %s found to be not latest, it was last modified: %s. Ignoring it.", *version.Key, *version.VersionId, version.LastModified)
```suggestion
					logrus.Warnf("Snapshot %s with versionID %s found not to be the latest version, it was last modified at %s. Ignoring it.", *version.Key, *version.VersionId, version.LastModified)
```

2025-01-02 14:30 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore_test.go
Can you please add some tests specific to handling immutable backups for S3 buckets? Like garbage collection for instance.

2025-01-03 04:36 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +		return true, objectConfig.ObjectLockConfiguration.Rule.DefaultRetention.Days, nil
here, it won't be an issue as caller for this func is checking the nil pointer reference.

```go
if bucketImmutableExpiryTimeInDays != nil {
....
}
```

2025-01-03 04:51 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
>  	}
done, PTAL

2025-01-03 04:51 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
>  }
done, PTAL

2025-01-03 04:51 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +	if *objectConfig.ObjectLockConfiguration.ObjectLockEnabled == "Enabled" {
thanks for pointing out. made the changes.

2025-01-03 05:11 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +								_, bucketImmutableExpiryTimeInDays, err = GetBucketImmutabilityTime(s)
yes, you are correct. Actually I added this in case of previous api call failed.
Another way to handle this is to add a retry mechanism in first api call, and remove this else handling part , wdyt ?

2025-01-03 05:21 UTC, ishan16696 commented
I have rebased the PR on master.

2025-01-03 07:27 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +								_, bucketImmutableExpiryTimeInDays, err = GetBucketImmutabilityTime(s)
Yes, retry mechanism seems more intuitive here.

2025-01-03 07:31 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +		return true, objectConfig.ObjectLockConfiguration.Rule.DefaultRetention.Days, nil
`bucketImmutableExpiryTimeInDays` is deduced from `GetBucketImmutabilityTime()`, which in turn returns `objectConfig.ObjectLockConfiguration.Rule.DefaultRetention.Days`. Simply checking `bucketImmutableExpiryTimeInDays` will not help, since you could have `Rule` an non-nil, but `DefaultRetention` could be nil, and throw an exception. That's the reason the entire path should be checked here.

2025-01-03 07:47 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +		return true, objectConfig.ObjectLockConfiguration.Rule.DefaultRetention.Days, nil
ok, got your point. I will make the change.

2025-01-06 08:05 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +		return true, objectConfig.ObjectLockConfiguration.Rule.DefaultRetention.Days, nil
made the changes. Also added a some unit tests for the same. PTAL

2025-01-06 08:06 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +								_, bucketImmutableExpiryTimeInDays, err = GetBucketImmutabilityTime(s)
made the changes, PTAL

2025-01-06 08:40 UTC, shreyas-s-rao requested changes
@ishan16696 thanks for addressing my review comments! Just a small nit, but overall LGTM.

2025-01-06 08:40 UTC, shreyas-s-rao commented on pkg/snapstore/snapstore_test.go
> +	var s3ObjectLockBucketBUTRulesNotDefined = "mock-s3ObjectLockBucketBUTRulesNotDefined"
Can you please add a comment about what `s3ObjectLockBucketBUTRulesNotDefined` exactly means here?

2025-01-07 04:21 UTC, shreyas-s-rao commented on pkg/snapstore/snapstore_test.go
> +	var s3ObjectLockBucketBUTRulesNotDefined = "mock-s3ObjectLockBucketBUTRulesNotDefined"
Ah then can you please rename to `s3ObjectLockBucketButRulesNotDefined`. The `BUT` was capitalized, so that threw me off, since I thought it was an abbreviation for something 😅

2025-01-07 04:25 UTC, ishan16696 commented on pkg/snapstore/snapstore_test.go
> +	var s3ObjectLockBucketBUTRulesNotDefined = "mock-s3ObjectLockBucketBUTRulesNotDefined"
ok, no worries, I will rename it.

2025-01-07 04:28 UTC, shreyas-s-rao approved these changes
/lgtm

2025-01-07 09:24 UTC, renormalize requested changes
Thanks for the PR @ishan16696!

There's a few places where I'd like to understand the code better, so I've left my review comments there.

2025-01-07 09:24 UTC, renormalize commented on pkg/snapstore/s3_snapstore.go
> +				if *version.IsLatest {
I do not understand why the latest version is being checked for here? Shouldn't we be checking for the **oldest** version?

Checking the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html):

> Placing a retention period or a legal hold on an object protects only the version that's specified in the request. Retention periods and legal holds don't prevent new versions of the object from being created, or delete markers to be added on top of the object.

If an object is uploaded, and for some reason a newer version is created, the *original* object is no longer `IsLatest == true`. The unwanted version will be `IsLatest == true`.

Can you please help me understand?

2025-01-07 09:24 UTC, renormalize commented on pkg/snapstore/s3_snapstore.go
> +					logrus.Warnf("Snapshot %s with versionID [%s] found not to be latest, it was last modified at %s. Ignoring it.", *version.Key, *version.VersionId, *version.LastModified)
If the versionID corresponds to *not* being the latest, wouldn't that mean the object was modified, and thus we need to find the oldest version?

2025-01-07 09:24 UTC, renormalize commented on pkg/snapstore/s3_snapstore.go
> +		if err := retry.OnError(retry.DefaultBackoff, func(err error) bool {
What's the reason behind implementing a retry mechanism for a standard S3 API call? Did you observe the request not responding at all?
If the response time is too long, perhaps we can make use of `GetObjectLockConfigurationWithContext`?

2025-01-07 09:24 UTC, renormalize commented on pkg/types/snapstore.go
> +	// Note: "includeAll" boolean is only applicable for storage provider: ABS and GCS.
What's the reason behind not supporting it for S3?
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html

2025-01-08 03:05 UTC, shreyas-s-rao commented on pkg/types/snapstore.go
> +	// It is used only for AWS S3 object lock immutability.
100% agree with you @renormalize . I also thought about this, but didn't want to bring it into the scope of this PR. Can you please raise an issue regarding this? If not now, we should definitely address this when refactoring the code.

2025-01-08 05:56 UTC, ishan16696 commented on pkg/types/snapstore.go
> +	// Note: "includeAll" boolean is only applicable for storage provider: ABS and GCS.
> What's the reason behind not supporting it for S3?

the reason is to get tag of any object, s3 client have to get all object first then make API call for each object, hence to avoid `n` api call for `n` object, I choose to go with different method.
I have mention this here in doc but I have only mention that this can be achieved with different method (soft delete in this case)
https://github.com/gardener/etcd-backup-restore/blob/295d4103ffd3366c514ee72936a9ba8899cd24ad/docs/usage/enabling_immutable_snapshots.md#aws-s3-1

2025-01-08 07:34 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +	// to delete non-versioned snapshots present in bucket.
made the changes, PTAL

2025-01-08 08:26 UTC, anveshreddy18 requested changes
Thanks for the PR @ishan166696. I have few basic nits PTAL, otherwise it looks good.

2025-01-08 08:26 UTC, anveshreddy18 commented on pkg/snapstore/s3_snapstore_test.go
> +	)
```suggestion
	var (
		count    int64
		limit    int64 = 1 // aws default is 1000.
		lastPage bool
		keys     []string
		out      = &s3.ListObjectVersionsOutput{
			Prefix:   in.Prefix,
			Versions: make([]*s3.ObjectVersion, 0),
		}
	)
```
Just a nit as the zero values are what you wanted only.

2025-01-08 08:26 UTC, anveshreddy18 commented on pkg/snapstore/s3_snapstore.go
> +			return nil
```suggestion
			if isObjectLockEnabled, bucketImmutableExpiryTimeInDays, err = GetBucketImmutabilityTime(s); err != nil {
				logrus.Errorf("unable to check bucket immutability retention period: %v", err)
				return err
			} else if !isObjectLockEnabled {
				logrus.Warnf("Bucket versioning is found to be enabled but object lock is not found to be enabled.")
				logrus.Warnf("Please enable the object lock for the given bucket to to have immutable snapshots.")
			} else if bucketImmutableExpiryTimeInDays == nil {
				logrus.Warnf("Object lock is found to be enabled but object lock rules or default retention period are not found to be set.")
			}
			return nil
```

Just to make sure the condition `isObjectLockEnabled` is checked only once. Feel free to ignore if you feel it doesn't matter.

2025-01-08 10:12 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +				if *version.IsLatest {
> for some reason a newer version is created

backup-restore don't perform any operation on snapshot once it is created, apart from GC which will be done after snapshot is no longer protected by object lock.

Right now, I'm only considering the latest snapshots while `listing` the snapshots from bucket, If snapshot found to be no longer latest then backup-restore will just print the warning. 
- It is done to avoid `tagging method to ignore the snapshots` as explain in this comment https://github.com/gardener/etcd-backup-restore/pull/818#discussion_r1906517909, tagging method is not feasible for S3.
- If you want your snapshot back, then simply remove the deletionMarker present for that particular snapshot.


> Shouldn't we be checking for the oldest version?

I got your point of checking the oldest snapshot, but then backup-restore won't be able to support feature of `ignoring any snapshots`. Moreover, this checking of oldest version is not full proof, take an illustration:

2025-01-08 10:29 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +			return nil
I have made the changes, PTAL

2025-01-08 10:29 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore_test.go
> +	)
pushed the changes.

2025-01-08 10:29 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +		// To fetch the versioned snapshots incase is object enabled for bucket.
done.

2025-01-08 11:53 UTC, anveshreddy18 approved these changes
lgtm!

2025-01-10 05:39 UTC, renormalize requested changes
Capturing @shreyas-s-rao's comment from a discussion offline.

2025-01-10 05:39 UTC, renormalize commented on pkg/snapstore/s3_snapstore.go
> +							snapList = append(snapList, snap)
The `List` call only appends only one particular version of the snapshot (in the current implementation, the latest) into the `snapList`. 
However, this would be not be sufficient for garbage collection since all versions should be returned by `List`, to ensure all versions are cleaned up.

2025-01-10 08:20 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +							snapList = append(snapList, snap)
Thanks for capturing this @renormalize . On those lines, there should ideally be a config item to tell the LIST call whether to return all versions of snapshots, or only a specific version. While garbage collection requires all versions, restoration will only require specific versions of the snapshots.

I increasingly feel that the `List()` method needs to have a `ListOptions` parameter which we can be used to pass provider-specific configs to the call. So that we don't blow up the List method parameters with a bunch of provider-specific arguments.

2025-01-10 08:44 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +							snapList = append(snapList, snap)
I disagree with your point of `List` call should return the all versions of snapshot.
I agree with the restoration point of view of this comment: https://github.com/gardener/etcd-backup-restore/pull/818#discussion_r1905135692 that our restoration should only consider the oldest version of snapshot, so that our restoration should use the snapshots created/uploaded by backup-restore as only those will be the oldest one, and any modification/corruption on top of snapshot should be ignored.
But here, GC should also garbage collect snapshot created/uploaded by backup-restore, if there are different versions of snapshot present then it's a indication of attack. We should use that info to detect attack rather than GC all the corrupted snapshot as well and with no information about the attack.

2025-01-10 08:51 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +				if *version.IsLatest {
As discussed offline with @renormalize and @shreyas-s-rao, we decided to that our restoration should only consider the oldest version of snapshot, so that our restoration should use the snapshots created/uploaded by backup-restore as only those will be the oldest one, and any modification/corruption on top of snapshot should be ignored.

2025-01-13 09:17 UTC, ishan16696 commented on pkg/types/snapstore.go
> +	// Note: "includeAll" boolean is only applicable for storage provider: ABS and GCS.
cc @seshachalam-yv

2025-01-14 19:43 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +				if *version.IsLatest {
I have addressed this. PTAL.

2025-01-15 03:44 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +					logrus.Warnf("Snapshot %s with versionID [%s] found not to be latest, it was last modified at %s. Ignoring it.", *version.Key, *version.VersionId, *version.LastModified)
https://github.com/gardener/etcd-backup-restore/pull/818#discussion_r1910015643

2025-01-15 05:42 UTC, renormalize commented on pkg/snapstore/s3_snapstore.go
> +							snapList = append(snapList, snap)
Thanks for your explanation @ishan16696! I understand your train of thought now.
I guess I am okay with this.

2025-01-15 07:04 UTC, renormalize requested changes
Thanks for the changes @ishan16696. I have a couple suggestions for the changes in 8141c0028c8490a23d85d74b331dc1e3affe2285.

Once these are addressed, it's an approval from my side.

2025-01-15 10:02 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +		allSnapKeysMapToVersionID := make(map[string]string)
yes, make sense

2025-01-15 10:04 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +					}
> There's only one situation where the map is not updated, when the map has a time.Time value present, and it is already (*version.LastModified).After(value)

yes, you are correct, I also thought that but to make code simple I choose this , so that anyone can understand code better as it improves the readability imo.

2025-01-15 10:05 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +		allSnapKeysMapToVersionID := make(map[string]string)
made the changes, PTAL.

2025-01-15 10:10 UTC, renormalize commented on pkg/snapstore/s3_snapstore.go
> +					}
I think the conditional expression I suggested is pretty simple to understand, but I don't have strong opinions on this. We can close this thread once shreyas-s-rao also takes a look.

2025-01-15 10:14 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +					}
ok, I also don't have strong opinion. It could be my personal bias as I like separate condition for better readability.
@shreyas-s-rao can take a look on this.

2025-01-15 15:52 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +							snapList = append(snapList, snap)
Ok, so you suggest that GC ignore the snapshots not created by etcdbr. That's a valid argument. But think of this scenario:
1. etcdbr uploads a set of snapshots
2. attacker creates a new version of a snapshot, so let's assume that `snapshot123` has a second version
3. GC runs, garbage collecting the oldest versions of the snapshots. The oldest version for `snapshot123` is deleted, while the new version of `snapshot123` remains.
4. Upon the next GC run, the only remaining version of `snapshot123` becomes the oldest snapshot now, and GC will anyway garbage collect it.

So the argument `GC should only garbage collect snapshots created by etcdbr` is no longer adhered to. So eventually, GC will anyway clean up all versions of a snapshot, with enough GC runs over time. Is that ok with you @ishan16696 ?

2025-01-15 16:31 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +					}
yeah, I will make the change ... no worries

2025-01-15 18:20 UTC, ishan16696 commented on pkg/snapstore/s3_snapstore.go
> +					}
I have made the change. PTAL

2025-01-16 05:45 UTC, shreyas-s-rao commented on pkg/snapstore/s3_snapstore.go
> +							snapList = append(snapList, snap)
In an out-of-band discussion between me, @ishan16696 and @renormalize , we decided that the scope of this PR is to prevent modification/deletion of objects, and not handle addition of new malicious objects. Restoration is not affected, since the code only fetches the oldest versions of the objects, so addition of new object versions will not cause any disruptions to the functioning of etcd-backup-restore. Hence, we can mark this comment as resolved, and revisit it once we take up the task of handling addition of malicious object versions.

2025-01-16 05:53 UTC, shreyas-s-rao approved these changes
@ishan16696 thanks a lot for making the requested changes!
/lgtm

2025-01-16 05:56 UTC, renormalize approved these changes

2025-01-16 10:20 UTC, merged